# Generated by Django 6.0 on 2025-12-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TripCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("current_cycle_used", models.FloatField()),
                ("total_distance", models.FloatField(blank=True, null=True)),
                ("total_driving_time", models.FloatField(blank=True, null=True)),
                ("total_trip_time", models.FloatField(blank=True, null=True)),
                ("route_data", models.JSONField(blank=True, null=True)),
                ("logs_data", models.JSONField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trip Calculation",
                "verbose_name_plural": "Trip Calculations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="route_calcu_created_5cfc0e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="route_calcu_status_65f9a6_idx"
                    ),
                ],
            },
        ),
    ]
