# Generated by Django 6.0 on 2025-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripcalculation",
            name="map_error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tripcalculation",
            name="map_file",
            field=models.ImageField(blank=True, null=True, upload_to="maps/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="tripcalculation",
            name="map_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tripcalculation",
            name="map_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tripcalculation",
            name="map_task_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="tripcalculation",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tripcalculation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="tripcalculation",
            index=models.Index(
                fields=["map_status"], name="route_calcu_map_sta_fb1d3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripcalculation",
            index=models.Index(
                fields=["status", "map_status"], name="route_calcu_status_b59ab5_idx"
            ),
        ),
    ]
