# Generated by Django 6.0 on 2025-12-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_calculator", "0002_tripcalculation_map_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripcalculation",
            name="map_url",
            field=models.URLField(
                blank=True,
                help_text="Cloudinary URL for production storage",
                max_length=500,
                null=True,
            ),
        ),
    ]
